# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: php:7.1-apache
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
      - image: circleci/mongo:4-ram

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends git unzip wget && wget https://getcomposer.org/download/1.6.5/composer.phar
      - run: chmod +x composer.phar && mv composer.phar /usr/local/bin/composer
      - run: apt-get install -y libzip-dev && pecl install zip && echo "extension=zip.so" >> /usr/local/etc/php/conf.d/zip.ini
      - run: pecl install mongodb && echo "extension=mongodb.so" >> /usr/local/etc/php/conf.d/mongo.ini
      - run: cd api && composer install -n --prefer-dist
      - run: cd api && ./bin/phpunit
      - run: php api/bin/console server:start
      - run: cd admin && yarn test
