# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: php:7.1-apache
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
      - image: circleci/mongo:4-ram

    working_directory: ~/repo

    steps:
      - checkout
      - run: pecl install mongodb
      - run: apt-get install -y --no-install-recommends git unzip wget
      - run: wget https://raw.githubusercontent.com/composer/getcomposer.org/fe44bd5b10b89fbe7e7fc70e99e5d1a344a683dd/web/installer -O - -q | php -- --quiet
      - run: cd api && composer install -n --prefer-dist
      - run: ./bin/phpunit