# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: php:7.1-apache
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
      - image: circleci/mongo:4-ram

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update
      # api testing
      - run: apt-get install -y --no-install-recommends git unzip wget && wget https://getcomposer.org/download/1.6.5/composer.phar
      - run: chmod +x composer.phar && mv composer.phar /usr/local/bin/composer
      - run: apt-get install -y libzip-dev && pecl install zip && docker-php-ext-enable zip
      - run: pecl install mongodb && docker-php-ext-enable mongodb
      - run: docker-php-ext-install pcntl
      - run: cd api && composer install -n --prefer-dist
      - run: cd api && ./bin/phpunit
      # admin testing
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: php api/bin/console server:start
      - run: cd admin && yarn install
      - run: cd admin && yarn test
